import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'dart:convert';
import '../../services/firebase_service.dart';
import '../../services/database_helper.dart';

class HistoryScreen extends StatefulWidget {
  @override
  _HistoryScreenState createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> with SingleTickerProviderStateMixin {
  final FirebaseService _db = FirebaseService();
  final DatabaseHelper _localDb = DatabaseHelper();
  late TabController _tabController;
  bool _isOfflineMode = false;
  List<Map<String, dynamic>> _offlineHistory = [];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _loadOfflineHistory();
  }

  Future<void> _loadOfflineHistory() async {
    final history = await _localDb.getAllPredictions();
    setState(() => _offlineHistory = history);
  }

  Future<void> _generatePdf(Map<String, dynamic> data, {bool isOffline = false}) async {
    final pdf = pw.Document();
    
    String title = isOffline ? _getModelTitle(data['model_type']) : data['title'];
    double riskScore = isOffline 
      ? (data['risk_score'] ?? 0.0) 
      : (data['riskScore'] ?? 0.0);
    String riskLevel = isOffline 
      ? (data['risk_level'] ?? 'Unknown')
      : (data['riskLevel'] ?? 'Unknown');
    
    pdf.addPage(pw.Page(
      build: (context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Header(
              level: 0,
              child: pw.Text("Explainable AI - Medical Report", 
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            ),
            pw.SizedBox(height: 20),
            
            pw.Text("Diagnosis: $title", style: pw.TextStyle(fontSize: 18)),
            pw.SizedBox(height: 10),
            pw.Text("Risk Level: $riskLevel", 
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.Text("Risk Score: ${(riskScore * 100).toStringAsFixed(1)}%"),
            pw.SizedBox(height: 20),
            
            if (!isOffline) ...[
              pw.Divider(),
              pw.Text("Doctor Review Status: ${data['status'] ?? 'Pending'}", 
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              if (data['doctorNotes']?.toString().isNotEmpty ?? false)
                pw.Text("Doctor Notes: ${data['doctorNotes']}"),
              pw.SizedBox(height: 10),
              if (data['reviewedBy']?.toString().isNotEmpty ?? false)
                pw.Text("Reviewed By: ${data['reviewedBy']}"),
            ],
            
            pw.SizedBox(height: 30),
            pw.Divider(),
            pw.SizedBox(height: 10),
            pw.Text(
              "Disclaimer: This report is generated by an AI system for informational purposes only. "
              "It should not be used as a substitute for professional medical advice, diagnosis, or treatment. "
              "Always consult a qualified healthcare provider.",
              style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic),
            ),
            pw.SizedBox(height: 10),
            pw.Text("Generated on: ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}",
              style: pw.TextStyle(fontSize: 10)),
          ],
        );
      },
    ));
    
    await Printing.layoutPdf(onLayout: (format) => pdf.save());
  }

  String _getModelTitle(String? modelType) {
    switch (modelType) {
      case 'heart': return 'Heart Disease';
      case 'diabetes': return 'Diabetes';
      case 'pneumonia': return 'Pneumonia';
      default: return 'Health Assessment';
    }
  }

  IconData _getModelIcon(String? modelType) {
    switch (modelType) {
      case 'heart': return Icons.favorite;
      case 'diabetes': return Icons.water_drop;
      case 'pneumonia': return Icons.image;
      default: return Icons.medical_services;
    }
  }

  Color _getModelColor(String? modelType) {
    switch (modelType) {
      case 'heart': return Colors.red;
      case 'diabetes': return Colors.blue;
      case 'pneumonia': return Colors.purple;
      default: return Colors.grey;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("My Medical History"),
        bottom: TabBar(
          controller: _tabController,
          tabs: [
            Tab(icon: Icon(Icons.cloud), text: "Cloud"),
            Tab(icon: Icon(Icons.phone_android), text: "Offline"),
          ],
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.refresh),
            onPressed: () {
              setState(() {});
              _loadOfflineHistory();
            },
          ),
        ],
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildCloudHistory(),
          _buildOfflineHistory(),
        ],
      ),
    );
  }

  Widget _buildCloudHistory() {
    return StreamBuilder<QuerySnapshot>(
      stream: _db.getPatientHistory(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }
        
        if (snapshot.hasError) {
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.cloud_off, size: 60, color: Colors.grey),
                SizedBox(height: 16),
                Text("Unable to connect to cloud", style: TextStyle(color: Colors.grey)),
                TextButton(
                  onPressed: () => _tabController.animateTo(1),
                  child: Text("View Offline History"),
                ),
              ],
            ),
          );
        }
        
        if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
          return _buildEmptyState();
        }

        var docs = snapshot.data!.docs;

        return ListView.builder(
          itemCount: docs.length,
          padding: EdgeInsets.all(10),
          itemBuilder: (context, index) {
            var data = docs[index].data() as Map<String, dynamic>;
            return _buildCloudHistoryCard(data);
          },
        );
      },
    );
  }

  Widget _buildCloudHistoryCard(Map<String, dynamic> data) {
    // UI logic for status
    IconData statusIcon = Icons.access_time;
    Color statusColor = Colors.orange;
    if (data['status'] == 'Confirmed') { statusIcon = Icons.check_circle; statusColor = Colors.green; }
    if (data['status'] == 'Rejected') { statusIcon = Icons.cancel; statusColor = Colors.red; }
    if (data['status'] == 'Needs Tests') { statusIcon = Icons.science; statusColor = Colors.blue; }

    String dateStr = "Unknown";
    if (data['timestamp'] != null) {
      dateStr = DateFormat('MMM d, yyyy - h:mm a').format(
        (data['timestamp'] as Timestamp).toDate()
      );
    }

    bool isHighRisk = (data['riskScore'] ?? 0) > 0.5;

    return Card(
      margin: EdgeInsets.only(bottom: 12),
      elevation: 2,
      child: ExpansionTile(
        leading: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: _getModelColor(data['title']?.toString().toLowerCase().split(' ')[0]).withOpacity(0.1),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(
            _getModelIcon(data['title']?.toString().toLowerCase().split(' ')[0]),
            color: _getModelColor(data['title']?.toString().toLowerCase().split(' ')[0]),
          ),
        ),
        title: Text(data['title'] ?? 'Assessment', style: TextStyle(fontWeight: FontWeight.bold)),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(height: 4),
            Row(
              children: [
                Icon(statusIcon, size: 14, color: statusColor),
                SizedBox(width: 5),
                Text(data['status'] ?? 'Pending', style: TextStyle(color: statusColor, fontSize: 12)),
              ],
            ),
            Text(dateStr, style: TextStyle(fontSize: 11, color: Colors.grey)),
          ],
        ),
        trailing: Container(
          padding: EdgeInsets.symmetric(horizontal: 10, vertical: 4),
          decoration: BoxDecoration(
            color: isHighRisk ? Colors.red.shade100 : Colors.green.shade100,
            borderRadius: BorderRadius.circular(12),
          ),
          child: Text(
            "${((data['riskScore'] ?? 0) * 100).toStringAsFixed(0)}%",
            style: TextStyle(
              fontWeight: FontWeight.bold,
              color: isHighRisk ? Colors.red : Colors.green,
            ),
          ),
        ),
        children: [
          Padding(
            padding: EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Risk Level
                Container(
                  padding: EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isHighRisk ? Colors.red.shade50 : Colors.green.shade50,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Icon(isHighRisk ? Icons.warning : Icons.check_circle, 
                        color: isHighRisk ? Colors.red : Colors.green),
                      SizedBox(width: 10),
                      Text(
                        "Risk Level: ${data['riskLevel'] ?? 'Unknown'}",
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 12),
                
                // Doctor's Notes
                Text("Doctor's Review:", style: TextStyle(fontWeight: FontWeight.bold)),
                SizedBox(height: 8),
                Container(
                  padding: EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.grey.shade100,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    data['doctorNotes']?.toString().isNotEmpty == true 
                      ? data['doctorNotes'] 
                      : "Awaiting doctor review...",
                    style: TextStyle(
                      fontStyle: data['doctorNotes']?.toString().isNotEmpty == true 
                        ? FontStyle.normal 
                        : FontStyle.italic,
                    ),
                  ),
                ),
                SizedBox(height: 16),
                
                // Download Button
                ElevatedButton.icon(
                  icon: Icon(Icons.picture_as_pdf),
                  label: Text("Download Report"),
                  onPressed: () => _generatePdf(data),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    foregroundColor: Colors.white,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildOfflineHistory() {
    if (_offlineHistory.isEmpty) {
      return _buildEmptyState(isOffline: true);
    }

    return RefreshIndicator(
      onRefresh: _loadOfflineHistory,
      child: ListView.builder(
        itemCount: _offlineHistory.length,
        padding: EdgeInsets.all(10),
        itemBuilder: (context, index) {
          var data = _offlineHistory[index];
          return _buildOfflineHistoryCard(data);
        },
      ),
    );
  }

  Widget _buildOfflineHistoryCard(Map<String, dynamic> data) {
    String modelType = data['model_type'] ?? '';
    String title = _getModelTitle(modelType);
    double riskScore = data['risk_score'] ?? 0.0;
    String riskLevel = data['risk_level'] ?? 'Unknown';
    bool isHighRisk = riskScore > 0.5;
    bool isSynced = data['synced'] == 1;
    
    String dateStr = "Unknown";
    if (data['timestamp'] != null) {
      dateStr = DateFormat('MMM d, yyyy - h:mm a').format(DateTime.parse(data['timestamp']));
    }

    return Card(
      margin: EdgeInsets.only(bottom: 12),
      elevation: 2,
      child: ExpansionTile(
        leading: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
            color: _getModelColor(modelType).withOpacity(0.1),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(_getModelIcon(modelType), color: _getModelColor(modelType)),
        ),
        title: Row(
          children: [
            Text(title, style: TextStyle(fontWeight: FontWeight.bold)),
            SizedBox(width: 8),
            Icon(
              isSynced ? Icons.cloud_done : Icons.cloud_off,
              size: 16,
              color: isSynced ? Colors.green : Colors.orange,
            ),
          ],
        ),
        subtitle: Text(dateStr, style: TextStyle(fontSize: 11, color: Colors.grey)),
        trailing: Container(
          padding: EdgeInsets.symmetric(horizontal: 10, vertical: 4),
          decoration: BoxDecoration(
            color: isHighRisk ? Colors.red.shade100 : Colors.green.shade100,
            borderRadius: BorderRadius.circular(12),
          ),
          child: Text(
            "${(riskScore * 100).toStringAsFixed(0)}%",
            style: TextStyle(
              fontWeight: FontWeight.bold,
              color: isHighRisk ? Colors.red : Colors.green,
            ),
          ),
        ),
        children: [
          Padding(
            padding: EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Risk Level
                Container(
                  padding: EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isHighRisk ? Colors.red.shade50 : Colors.green.shade50,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Icon(isHighRisk ? Icons.warning : Icons.check_circle, 
                        color: isHighRisk ? Colors.red : Colors.green),
                      SizedBox(width: 10),
                      Text("Risk Level: $riskLevel", style: TextStyle(fontWeight: FontWeight.bold)),
                    ],
                  ),
                ),
                SizedBox(height: 12),
                
                // Sync Status
                Container(
                  padding: EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isSynced ? Colors.green.shade50 : Colors.orange.shade50,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        isSynced ? Icons.cloud_done : Icons.cloud_upload,
                        color: isSynced ? Colors.green : Colors.orange,
                      ),
                      SizedBox(width: 10),
                      Text(
                        isSynced ? "Synced to cloud" : "Stored locally (will sync when online)",
                        style: TextStyle(fontSize: 13),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 16),
                
                // Download Button
                ElevatedButton.icon(
                  icon: Icon(Icons.picture_as_pdf),
                  label: Text("Download Report"),
                  onPressed: () => _generatePdf(data, isOffline: true),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    foregroundColor: Colors.white,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState({bool isOffline = false}) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            isOffline ? Icons.phone_android : Icons.history,
            size: 80,
            color: Colors.grey.shade400,
          ),
          SizedBox(height: 16),
          Text(
            isOffline ? "No offline records" : "No medical records yet",
            style: TextStyle(fontSize: 18, color: Colors.grey.shade600),
          ),
          SizedBox(height: 8),
          Text(
            isOffline 
              ? "Records will be stored here when you're offline"
              : "Complete an AI health screening to see your history",
            style: TextStyle(color: Colors.grey),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }
}
