// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2wpVyGHUqOj9uPZqoojIcQClWE1mC1BI',
    appId: '1:475478277892:web:1cadfb735960d1bf751a51',
    messagingSenderId: '475478277892',
    projectId: 'explainableai-1a76c',
    authDomain: 'explainableai-1a76c.firebaseapp.com',
    storageBucket: 'explainableai-1a76c.firebasestorage.app',
    measurementId: 'G-X4HVKVZZEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4UfNewG_1yJhsTnTDlpMKTMdFwQYVZSo',
    appId: '1:475478277892:android:4a211dbffc0cb744751a51',
    messagingSenderId: '475478277892',
    projectId: 'explainableai-1a76c',
    storageBucket: 'explainableai-1a76c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRrLA_etApjZdt8eJbBNWs1aq1k0Lc2g',
    appId: '1:475478277892:ios:eb45283f3c6265e6751a51',
    messagingSenderId: '475478277892',
    projectId: 'explainableai-1a76c',
    storageBucket: 'explainableai-1a76c.firebasestorage.app',
    iosBundleId: 'com.example.explainableAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqRrLA_etApjZdt8eJbBNWs1aq1k0Lc2g',
    appId: '1:475478277892:ios:eb45283f3c6265e6751a51',
    messagingSenderId: '475478277892',
    projectId: 'explainableai-1a76c',
    storageBucket: 'explainableai-1a76c.firebasestorage.app',
    iosBundleId: 'com.example.explainableAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2wpVyGHUqOj9uPZqoojIcQClWE1mC1BI',
    appId: '1:475478277892:web:af73c2cdf3483f8d751a51',
    messagingSenderId: '475478277892',
    projectId: 'explainableai-1a76c',
    authDomain: 'explainableai-1a76c.firebaseapp.com',
    storageBucket: 'explainableai-1a76c.firebasestorage.app',
    measurementId: 'G-426L05L9WL',
  );
}